---
title: Hessam
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
url: https://hessams.github.io
baseurl: "/"
markdown: kramdown
tracking_id: 
sass:
  style: compressed
  sass_dir: _sass
