---
title: Researcher
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
url: http://ankitsultana.com
baseurl: "/researcher"
markdown: kramdown
tracking_id: 
sass:
  style: compressed
  sass_dir: _sass
